### ISSUE TITLE
R1 Support?

### ISSUE THREAD

**Issue by marleyjaffe** [Nuix/Nuix-Relativity-Connector#1]
Do you know if this connector supports R1 or will this only work for OnPrem Relativity environments?

**Comment by marleyjaffe** [comment]
R1 being RelativityOne, their SAAS offering.

**Comment by JuicyDragon** [comment]
Hello @marleyjaffe I inquired about your question and yes you can make use of this with RelativityOne if used in the `Loadfile Upload Mode` (not the `SQL/Fileshare` mode).  It does require a small update to the Nuget dependencies for the C# client.

To update the C# client to work with the current version of RelativityOne, you could modify the `10.2` client to remove the `Relativity.Import.Client` Nuget package (this is now deprecated) and replace it with the latest version of the `Relativity.DataExchange.Client.SDK` Nuget package (see https://www.nuget.org/packages/Relativity.DataExchange.Client.SDK/).
