### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by BashaManik** [Nuix/Nuix-Relativity-Connector#3]
Hi @JuicyDragon / @MisterMuezza 

I am trying to set up NUIX-Relativity Connector using ruby but facing few issues. Could you please instruct or elaborate more on Ruby set up in NUIX.

Thank you in Advance.

**Comment by JuicyDragon** [comment]
Hello @BashaManik could you elaborate a bit on the issue you are seeing?  Are you seeing a particular error?

**Comment by JuicyDragon** [comment]
Closing due to no response
